#lising of experimental settings in tab separated file

#Use simulated data?
simulation: yes

#Working directory
wd:
#How many cores to use for the workflow
ncore: 4

######### SIMULATION PARAMS ########
sim_pops: 10
sim_ind: 1000
sim_sites: 1000
sim_h2: 0.3
sim_MAF: 0.01
sim_threshold: 0.2

######### DATA PARAMS ########
# List of SNPs to use
snp_list: "extdata/"
# Pool_rc file
pool_rc: "example_pool_rc"
# File containing info on pools
pool_info: "example_pop_data.csv"
# File containing info on test individuals
ind_info: "example_ind_info.csv"
# VCF file for test samples
vcf: